WITH 
Shortest AS (SELECT CITY,LENGTH(CITY) AS CITY_LENGTH FROM STATION ORDER BY LENGTH(CITY) ASC,CITY ASC LIMIT 1),
Longest AS (SELECT CITY,LENGTH(CITY) AS CITY_LENGTH FROM STATION ORDER BY LENGTH(CITY) DESC,CITY ASC LIMIT 1)
SELECT * FROM Shortest UNION SELECT * FROM Longest;

# Problem: Some Engines do not accept that FETCH FIRST or ORDER BY will be done on the same level as UNION. Solution: CTE
